# Generated by Django 4.2.1 on 2023-05-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=200, verbose_name='text1')),
                ('text2', models.CharField(max_length=200, verbose_name='text2')),
                ('text3', models.CharField(max_length=200, verbose_name='text3')),
                ('text4', models.CharField(max_length=200, verbose_name='text4')),
                ('p1', models.CharField(max_length=100, verbose_name='p1')),
                ('p2', models.CharField(max_length=100, verbose_name='p2')),
                ('p3', models.CharField(max_length=100, verbose_name='p3')),
                ('p4', models.CharField(max_length=100, verbose_name='p4')),
                ('p5', models.CharField(max_length=100, verbose_name='p5')),
                ('button', models.CharField(max_length=50, verbose_name='button')),
                ('img', models.ImageField(upload_to='images', verbose_name='image')),
            ],
        ),
    ]
