# Generated by Django 4.2.1 on 2023-05-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_button_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button_1',
            name='text4',
        ),
    ]
