# Generated by Django 4.2.1 on 2023-05-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_button_1_text4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=200, verbose_name='text1')),
                ('icon', models.ImageField(upload_to='images', verbose_name='icon')),
                ('image_sm', models.ImageField(upload_to='images', verbose_name='Image sm')),
                ('image_big', models.ImageField(upload_to='images', verbose_name='Image big')),
            ],
        ),
    ]
