# Generated by Django 4.2.1 on 2023-05-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_button_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=200, verbose_name='text1')),
                ('icon', models.ImageField(upload_to='images', verbose_name='icon')),
                ('image_sm', models.ImageField(upload_to='images', verbose_name='Image sm')),
                ('image_big', models.ImageField(upload_to='images', verbose_name='Image big')),
            ],
        ),
        migrations.RemoveField(
            model_name='button_2',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='button_2',
            name='image_big',
        ),
        migrations.RemoveField(
            model_name='button_2',
            name='image_sm',
        ),
        migrations.AddField(
            model_name='button_2',
            name='img',
            field=models.ImageField(default=1, upload_to='images', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='button_2',
            name='p1',
            field=models.CharField(default=1, max_length=200, verbose_name='p1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='button_2',
            name='p2',
            field=models.CharField(default=1, max_length=200, verbose_name='p2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='button_2',
            name='p3',
            field=models.CharField(default=1, max_length=200, verbose_name='p3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='button_2',
            name='p4',
            field=models.CharField(default=1, max_length=200, verbose_name='p4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='button_2',
            name='p5',
            field=models.CharField(default=1, max_length=200, verbose_name='p5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='button_2',
            name='p6',
            field=models.CharField(default=1, max_length=200, verbose_name='p6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='button_2',
            name='text2',
            field=models.CharField(default=1, max_length=200, verbose_name='text2'),
            preserve_default=False,
        ),
    ]
