# Generated by Django 4.2 on 2023-05-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_button_3_remove_button_2_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('text1', models.TextField(verbose_name='text 1')),
                ('text2', models.TextField(verbose_name='text 2')),
                ('address1', models.CharField(max_length=100, verbose_name='Address 1')),
                ('address2', models.CharField(max_length=100, verbose_name='Address 2')),
                ('button', models.CharField(max_length=20, verbose_name='button')),
            ],
        ),
    ]
