# Generated by Django 4.2 on 2023-05-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_text_footer_text1_footer_text2'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='link_name',
            field=models.CharField(default=1, max_length=100, verbose_name='link name'),
            preserve_default=False,
        ),
    ]
